[package]
name = "rotom-dc-rs"
version = "0.0.0"
authors = ["Felipe Neves <ryukokki.felipe@gmail.com>"]
repository = "https://github.com/uLipe/rotom-rs"
description = """A Platform independent, vector controller for PMSM motors"""
categories = ["no-std"]
license = "MIT"

